# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/acer/Pulpit/IPP/duże

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/acer/Pulpit/IPP/duże/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/acer/Pulpit/IPP/duże/src/CMakeFiles /home/acer/Pulpit/IPP/duże/src//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/acer/Pulpit/IPP/duże/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named phone_forward

# Build rule for target.
phone_forward: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 phone_forward
.PHONY : phone_forward

# fast build rule for target.
phone_forward/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phone_forward.dir/build.make CMakeFiles/phone_forward.dir/build
.PHONY : phone_forward/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

list_of_numbers.o: list_of_numbers.c.o
.PHONY : list_of_numbers.o

# target to build an object file
list_of_numbers.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phone_forward.dir/build.make CMakeFiles/phone_forward.dir/list_of_numbers.c.o
.PHONY : list_of_numbers.c.o

list_of_numbers.i: list_of_numbers.c.i
.PHONY : list_of_numbers.i

# target to preprocess a source file
list_of_numbers.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phone_forward.dir/build.make CMakeFiles/phone_forward.dir/list_of_numbers.c.i
.PHONY : list_of_numbers.c.i

list_of_numbers.s: list_of_numbers.c.s
.PHONY : list_of_numbers.s

# target to generate assembly for a file
list_of_numbers.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phone_forward.dir/build.make CMakeFiles/phone_forward.dir/list_of_numbers.c.s
.PHONY : list_of_numbers.c.s

phnum.o: phnum.c.o
.PHONY : phnum.o

# target to build an object file
phnum.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phone_forward.dir/build.make CMakeFiles/phone_forward.dir/phnum.c.o
.PHONY : phnum.c.o

phnum.i: phnum.c.i
.PHONY : phnum.i

# target to preprocess a source file
phnum.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phone_forward.dir/build.make CMakeFiles/phone_forward.dir/phnum.c.i
.PHONY : phnum.c.i

phnum.s: phnum.c.s
.PHONY : phnum.s

# target to generate assembly for a file
phnum.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phone_forward.dir/build.make CMakeFiles/phone_forward.dir/phnum.c.s
.PHONY : phnum.c.s

phone_forward.o: phone_forward.c.o
.PHONY : phone_forward.o

# target to build an object file
phone_forward.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phone_forward.dir/build.make CMakeFiles/phone_forward.dir/phone_forward.c.o
.PHONY : phone_forward.c.o

phone_forward.i: phone_forward.c.i
.PHONY : phone_forward.i

# target to preprocess a source file
phone_forward.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phone_forward.dir/build.make CMakeFiles/phone_forward.dir/phone_forward.c.i
.PHONY : phone_forward.c.i

phone_forward.s: phone_forward.c.s
.PHONY : phone_forward.s

# target to generate assembly for a file
phone_forward.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phone_forward.dir/build.make CMakeFiles/phone_forward.dir/phone_forward.c.s
.PHONY : phone_forward.c.s

phone_forward_example.o: phone_forward_example.c.o
.PHONY : phone_forward_example.o

# target to build an object file
phone_forward_example.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phone_forward.dir/build.make CMakeFiles/phone_forward.dir/phone_forward_example.c.o
.PHONY : phone_forward_example.c.o

phone_forward_example.i: phone_forward_example.c.i
.PHONY : phone_forward_example.i

# target to preprocess a source file
phone_forward_example.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phone_forward.dir/build.make CMakeFiles/phone_forward.dir/phone_forward_example.c.i
.PHONY : phone_forward_example.c.i

phone_forward_example.s: phone_forward_example.c.s
.PHONY : phone_forward_example.s

# target to generate assembly for a file
phone_forward_example.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phone_forward.dir/build.make CMakeFiles/phone_forward.dir/phone_forward_example.c.s
.PHONY : phone_forward_example.c.s

phone_reverse.o: phone_reverse.c.o
.PHONY : phone_reverse.o

# target to build an object file
phone_reverse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phone_forward.dir/build.make CMakeFiles/phone_forward.dir/phone_reverse.c.o
.PHONY : phone_reverse.c.o

phone_reverse.i: phone_reverse.c.i
.PHONY : phone_reverse.i

# target to preprocess a source file
phone_reverse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phone_forward.dir/build.make CMakeFiles/phone_forward.dir/phone_reverse.c.i
.PHONY : phone_reverse.c.i

phone_reverse.s: phone_reverse.c.s
.PHONY : phone_reverse.s

# target to generate assembly for a file
phone_reverse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phone_forward.dir/build.make CMakeFiles/phone_forward.dir/phone_reverse.c.s
.PHONY : phone_reverse.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... doc"
	@echo "... phone_forward"
	@echo "... list_of_numbers.o"
	@echo "... list_of_numbers.i"
	@echo "... list_of_numbers.s"
	@echo "... phnum.o"
	@echo "... phnum.i"
	@echo "... phnum.s"
	@echo "... phone_forward.o"
	@echo "... phone_forward.i"
	@echo "... phone_forward.s"
	@echo "... phone_forward_example.o"
	@echo "... phone_forward_example.i"
	@echo "... phone_forward_example.s"
	@echo "... phone_reverse.o"
	@echo "... phone_reverse.i"
	@echo "... phone_reverse.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

